# Assignment 1 : Question 1

Simple TensorFlow exercises

In [1]:
import tensorflow as tf

Question 1a: Create two random 0-d tensors x and y of any distribution.
Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.

In [2]:
x=tf.random_uniform([],maxval=10,dtype=tf.int32)
y=tf.random_uniform([],maxval=10,dtype=tf.int32)

In [3]:
ans=tf.cond(x>y,lambda  : tf.add(x,y),lambda : tf.subtract(x,y))

In [4]:
sess=tf.Session()
print (sess.run([x,y]))
print (sess.run(ans))


[8, 0]
8


In [5]:
sess.close()

 Question 1b: Create two 0-d tensors x and y randomly selected from the range [-1, 1).
Return x + y if x < y, x - y if x > y, 0 otherwise.

In [6]:
x=tf.random_uniform([],minval=-1,maxval=1)
y=tf.random_uniform([],minval=-1,maxval=1)

In [7]:
ans=tf.case({ tf.less(x,y) : lambda : tf.add(x,y), tf.greater(x,y) :lambda : tf.subtract(x,y)},
            default=lambda :tf.constant(0.0),exclusive=True)

In [8]:
sess=tf.Session()
print (sess.run([x,y]))
print (sess.run(ans))

[0.92329192, -0.59817386]
0.570207


<b>Question 1c:</b> Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
and y as a tensor of zeros with the same shape as x.
 Return a boolean tensor that yields Trues if x equals y element-wise.


In [9]:
x = tf.constant([[0, -2, -1], [0, 1, 2]])
y = tf.zeros_like(x)
out = tf.equal(x, y)

In [10]:
sess=tf.Session()
print (sess.run([x,y]))
print (sess.run(out))

[array([[ 0, -2, -1],
       [ 0,  1,  2]], dtype=int32), array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)]
[[ True False False]
 [ True False False]]


<b>Question 1d:</b> Create the tensor x of value 
[29.05088806,  27.61298943,  31.19073486,  29.35532951,
  30.97266006,  26.67541885,  38.08450317,  20.74983215,
  34.94445419,  34.45999146,  29.06485367,  36.01657104,
  27.88236427,  20.56035233,  30.20379066,  29.51215172,
  33.71149445,  28.59134293,  36.05556488,  28.66994858].
 Get the indices of elements in x whose values are greater than 30.

In [11]:
x=tf.constant([29.05088806, 27.61298943, 31.19073486, 29.35532951, 30.97266006, 26.67541885, 38.08450317, 20.74983215, 34.94445419, 34.45999146, 29.06485367, 36.01657104, 27.88236427, 20.56035233, 30.20379066, 29.51215172, 33.71149445, 28.59134293, 36.05556488, 28.66994858])
ans=tf.gather(x,tf.where(x>30))


In [12]:
sess=tf.Session()
print(sess.run(ans))

[[ 31.19073486]
 [ 30.97266006]
 [ 38.08450317]
 [ 34.94445419]
 [ 34.45999146]
 [ 36.01657104]
 [ 30.20379066]
 [ 33.71149445]
 [ 36.05556488]]


<b>Question 1e:</b> Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
 2, ..., 6

In [13]:
ans=tf.diag(tf.range(1,7))

In [14]:
sess=tf.Session()
print(sess.run(ans))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


<b>Question 1f:</b> Create a random 2-d tensor of size 10 x 10 from any distribution.
Calculate its determinant.

In [15]:
x=tf.random_uniform([10,10],minval=1,maxval=5)
ans=tf.matrix_determinant(x)

In [16]:
sess=tf.Session()

print(sess.run([x,ans]))

[array([[ 4.73287964,  4.56933022,  4.02512741,  3.544662  ,  4.47268724,
         1.46814919,  4.28091526,  2.78769016,  4.01074266,  4.38095474],
       [ 3.74490213,  1.93239594,  1.88412905,  4.58691645,  4.25411081,
         2.74320364,  3.39694929,  3.33216   ,  2.44423151,  4.79859114],
       [ 4.07622147,  2.12457418,  4.84872007,  2.64596748,  1.41012955,
         2.34250164,  3.84238386,  2.62155581,  3.24905729,  3.30154943],
       [ 3.78132153,  3.27205467,  3.45041418,  4.9448576 ,  4.82873106,
         4.12736177,  3.99810076,  3.97567797,  4.10079527,  2.96157694],
       [ 2.84737062,  4.31518412,  1.42154503,  4.87606955,  3.89097166,
         3.56594419,  4.29971886,  3.06715536,  3.55072069,  3.75567293],
       [ 4.75471783,  1.84883547,  1.85778332,  4.82161427,  3.33157635,
         1.65908098,  4.01756525,  3.35624123,  1.90919828,  4.35374165],
       [ 4.7252779 ,  1.74656534,  2.3051486 ,  4.4815321 ,  1.37404728,
         1.72879791,  2.23088503,  2.2349371

<b>Question 1g:</b> Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
Return the unique elements in x

In [17]:
x=tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
num,index=tf.unique(x) #we get an array contatining unique elements and indexes of the elements in the output array

In [18]:
sess=tf.Session()
print(sess.run([num,index])) 

[array([ 5,  2,  3, 10,  6,  4,  1,  0,  9], dtype=int32), array([0, 1, 2, 0, 3, 4, 1, 2, 5, 1, 6, 6, 7, 8], dtype=int32)]


<b>Question 1h:</b> Create two tensors x and y of shape 300 from any normal distribution,
as long as they are from the same distribution.
 Use tf.cond() to return:
 - The mean squared error of (x - y) if the average of all elements in (x - y)
   is negative, or
 - The sum of absolute value of all elements in the tensor (x - y) otherwise.

In [19]:
x=tf.random_uniform([300],maxval=5)
y=tf.random_uniform([300],maxval=5)

In [20]:
ans = tf.cond(tf.reduce_mean(x-y)<0,lambda : tf.reduce_mean(tf.square(x-y)),lambda : tf.abs(x-y))

In [21]:
sess=tf.Session()
sess.run(ans)

4.8995214